# -*- coding: utf-8 -*-
"""agent.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1f2_f25ZW_dPsHu_-8m9vyOagAHlc0Cal
"""

!pip install -q transformers accelerate sentencepiece

from transformers import AutoTokenizer, AutoModelForCausalLM
import torch

model_name = "TinyLlama/TinyLlama-1.1B-Chat-v1.0"

tokenizer = AutoTokenizer.from_pretrained(model_name)

model = AutoModelForCausalLM.from_pretrained(
    model_name,
    torch_dtype=torch.float16,
    device_map="auto"
)

if tokenizer.pad_token is None:
    tokenizer.pad_token = tokenizer.eos_token

def llm(messages):  # 改成接收 messages
    prompt = tokenizer.apply_chat_template(
        messages, tokenize=False, add_generation_prompt=True
    )

    inputs = tokenizer(prompt, return_tensors="pt")
    inputs = {k: v.to(model.device) for k, v in inputs.items()}

    output = model.generate(
        **inputs,
        max_new_tokens=200,
        do_sample=False,
        pad_token_id=tokenizer.pad_token_id,
        eos_token_id=tokenizer.eos_token_id
    )

    new_tokens = output[0][inputs["input_ids"].shape[1]:]
    return tokenizer.decode(new_tokens, skip_special_tokens=True)

def calculator(expression):
    try:
        return str(eval(expression))
    except:
        return "計算錯誤"

system_prompt = """你是一個 AI Agent，你有以下工具可以使用：

CALCULATOR: 用來計算數學，格式是 CALCULATOR(算式)

如果需要計算，就輸出：CALCULATOR(算式)
如果不需要工具，直接回答。

範例：
User: 25 * 4 是多少？
Assistant: CALCULATOR(25 * 4)
"""

import re

def agent(user_question):
    messages = [
        {"role": "system", "content": system_prompt},
        {"role": "user", "content": user_question}
    ]

    response = llm(messages)
    print(f"模型說：{response}")

    if "CALCULATOR(" in response:
        expr = re.search(r"CALCULATOR\((.+)\)", response).group(1)
        print(f"呼叫計算機：{expr}")

        result = calculator(expr)
        print(f"計算結果：{result}")

        messages.append({"role": "assistant", "content": response})
        messages.append({"role": "user", "content": f"計算結果是 {result}，請給出最終回答"})

        final = llm(messages)
        return final

    return response

print(agent("15 * 12 是多少？"))